import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// next/font — self-hosted, display: swap. Swap the family per brand in /site-builder:tokens.
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans-stack",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Site Builder Starter",
  description: "A high-end, tested Next.js starter generated by site-builder.",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="bg-bg text-fg font-sans antialiased">{children}</body>
    </html>
  );
}
